service: image-catcher

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  stg: dev

functions:
  linebot:
    handler: line_lambda.linebot
    events:
      - http:
          path: linebot/post
          method: post
  main:
    handler: line_lambda.main

plugins:
  - serverless-offline
  - serverless-python-requirements

resources:
  Resources:
    StaticContentS3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service.name}-${opt:stage, self:provider.stage}-asset
